name: Rust

on:
  push:
    branches: [ main ]
<<<<<<< HEAD
  pull_request:
=======
  pull_requests:
>>>>>>> dd414cca611667950cb0f70236e39a7dea1cddc5
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo Build
        run: cargo build --verbose
      - name: Cargo Test
        run: cargo test --verbose
